/**
 * APP ROOT
 * ========
 * The main entry point of the React application.
 *
 * Responsibilities:
 * 1. Bootstrapping: Fetching the 'manifest.json' and initializing the Store.
 * 2. Layout: Setting up the full-screen container and R3F Canvas.
 * 3. Composition: Rendering the CameraRig, Overlay, and the InfiniteCanvas instances.
 */

// React Core
import React, { useEffect, Suspense } from 'react';

// React Three Fiber (R3F) - The React renderer for Three.js
import { Canvas } from '@react-three/fiber';

// R3F Helpers - Loader is a pre-made loading screen
import { Loader } from '@react-three/drei';

// Global State Management (Zustand)
import useStore from './store/useStore';

// Custom 3D Components
import CameraRig from './canvas/CameraRig';     // Handles camera movement logic
import InfiniteCanvas from './canvas/InfiniteCanvas'; // The main artwork renderer

// Custom UI Components
import Overlay from './components/Overlay';     // The 2D HTML Interface

const App = () => {
  // --- STATE SUBSCRIPTION ---
  // We select specific pieces of state from the store to minimize re-renders.

  // Action to populate the store with initial data
  const setManifest = useStore(state => state.setManifest);

  // Action to force a specific artwork to be active
  const setActiveId = useStore(state => state.setActiveId);

  // The ID of the currently focused artwork
  const activeId = useStore(state => state.activeId);

  // The ID of the artwork we are transitioning TOWARDS
  const nextId = useStore(state => state.nextId);

  // A value from 0.0 to 1.0 representing the journey from activeId to nextId
  const transitionProgress = useStore(state => state.transitionProgress);

  // --- 1. INITIALIZATION ---
  // Run once on mount to load the data.
  useEffect(() => {
    // Fetch the artwork graph generated by the Indexer script.
    fetch('/manifest.json')
      .then(res => {
        // Basic error handling for network issues
        if (!res.ok) throw new Error(`HTTP error! Status: ${res.status}`);
        return res.json();
      })
      .then(data => {
        // Validate that we actually got nodes
        if (!data.nodes || Object.keys(data.nodes).length === 0) {
          console.error("Manifest is empty or invalid.");
          return;
        }

        // Hydrate Store: Pass the raw node list to the store logic
        setManifest(data.nodes);

        // CHAOS SELECTION:
        // Pick a random artwork to start with, rather than a fixed homepage.
        // This ensures every visit is unique and encourages exploration.
        const keys = Object.keys(data.nodes);
        const randomId = keys[Math.floor(Math.random() * keys.length)];

        // Initialize the active artwork.
        // We use the store's action if available, or fallback to direct state manipulation if needed.
        if (setActiveId) {
            setActiveId(randomId);
        } else {
            // Fallback for robustness
            useStore.setState({ activeId: randomId });
        }
        
        console.log("System Initialized. Random Start:", randomId);
      })
      .catch(err => console.error("Manifest Load Failed:", err));
  }, [setManifest, setActiveId]); // Dependencies ensure this hook behaves correctly if store references change (unlikely)

  // --- RENDER ---
  return (
    // FULLSCREEN CONTAINER
    // Essential for the Canvas to take up the whole window.
    // We set a dark background color to match the void aesthetic.
    <div style={{ width: '100vw', height: '100vh', background: '#050505' }}>

      {/* 3D SCENE CANVAS */}
      <Canvas
        // Camera Config:
        // position: [x, y, z]. We start 5 units back (Z=5).
        // fov: Field of View. 75 is standard for wide-angle.
        camera={{ position: [0, 0, 5], fov: 75 }}

        // GL Config:
        // antialias: false. Disabling AA improves performance significantly for particle clouds.
        // alpha: false. We don't need a transparent canvas, so we save resources.
        gl={{ antialias: false, alpha: false }}

        // Pixel Ratio Config:
        // [1, 2] caps the DPI at 2x. Prevents mobile devices with 3x/4x screens from melting.
        dpr={[1, 2]}
      >
        {/* Set the WebGL clear color to match the container */}
        <color attach="background" args={['#050505']} />

        {/* SUSPENSE BOUNDARY */}
        {/* Handles async loading of 3D assets. 'fallback={null}' means we don't show a 3D loader,
            we rely on the <Loader /> component below the Canvas instead. */}
        <Suspense fallback={null}>

          {/* CAMERA RIG */}
          {/* This component has no visual output. It attaches to the camera and controls its movement. */}
          <CameraRig />

          {/* ACTIVE ARTWORK (Foreground) */}
          {/* This is the painting we are currently looking at. */}
          {activeId && (
            <group position={[0, 0, 0]}>
              <InfiniteCanvas
                activePaintingId={activeId}
                transitionProgress={transitionProgress}
              />
            </group>
          )}

          {/* NEXT ARTWORK (Background / Lookahead) */}
          {/* This is the painting waiting at the end of the tunnel (Z = -20).
              As transitionProgress increases, the Camera moves from Z=5 to Z=-5.
              Eventually, we swap them. */}
          {nextId && (
            <group position={[0, 0, -20]}>
              <InfiniteCanvas
                activePaintingId={nextId}
                transitionProgress={0} // The next one is static until we switch to it
              />
            </group>
          )}

          {/* LIGHTING */}
          {/* Ambient light ensures everything is visible. */}
          <ambientLight intensity={0.2} />
          {/* SpotLight adds dimension/specularity to the strokes (if they used standard materials). */}
          <spotLight position={[10, 10, 10]} intensity={1} angle={0.5} penumbra={1} />

        </Suspense>
      </Canvas>
      
      {/* LOADING INDICATOR */}
      {/* An HTML overlay provided by @react-three/drei that shows download progress. */}
      <Loader />

      {/* 2D HUD */}
      {/* The User Interface (Title, Navigation, etc.) rendered as standard HTML on top of the Canvas. */}
      <Overlay />
    </div>
  );
};

export default App;
